export const SELECT = 'SELECT'
export const SELECT_ALL = 'SELECT_ALL'
export const FILTER_ALL_OFF = 'FILTER_ALL_OFF'
export const SORT = 'SORT'
// export const REQUEST_SEARCH_ID = 'REQUEST_SEARCH_ID';
// export const RECEIVE_SEARCH_ID = 'RECEIVE_SEARCH_ID';
// export const REQUEST_TICKETS = 'REQUEST_TICKETS';
// export const RECEIVE_TICKETS = 'RECEIVE_TICKETS';
export const SORT_CHEAPEST_FIRST = 'SORT_CHEAPEST_FIRST';
export const SORT_FASTEST_FIRST = 'SORT_FASTEST_FIRST';
// export const RECEIVE_ERROR = 'RECEIVE_ERROR';
// export const IGNORE_ERROR = 'IGNORE_ERROR';
// export const TRANSFERS = 'TRANSFERS'
// export const SORT = 'SORT'
export const LOAD_TICKETS = 'LOAD_TICKETS'
export const SHOW_MORE = 'SHOW_MORE'
export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON'
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF'
export const GET_SEARCH_ID = 'GET_SEARCH_ID'
export const ERROR_ON = 'ERROR_ON'